name: Node.js CI with Build Logs

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create logs directory
        run: mkdir -p shared_logs

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies and log
        run: |
          echo "$(date) - Installing dependencies..." > shared_logs/build.log
          npm install >> shared_logs/build.log 2>&1

      - name: Run lint and log
        run: |
          echo "$(date) - Running lint..." >> shared_logs/build.log
          npm run lint >> shared_logs/build.log 2>&1 || echo "Lint issues found (non-blocking)" >> shared_logs/build.log

      - name: Run tests and log
        run: |
          echo "$(date) - Running tests..." >> shared_logs/build.log
          npm test >> shared_logs/build.log 2>&1

      - name: Upload build log
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: shared_logs/build.log
          retention-days: 5

      - name: Display log tail (debug)
        run: tail -n 20 shared_logs/build.log
